using UnityEngine;

public class DontDestroyOnLoad : MonoBehaviour
{
    private void Awake()
    {
        DontDestroyOnLoad[] objs = FindObjectsOfType<DontDestroyOnLoad>();

        if (objs.Length > 2)
        {
            if (this)
            {
                Destroy(gameObject);
            }
        }

        DontDestroyOnLoad(this);
    }

    // I wanna kill myself

    /* 
    MMMMMMMMMMMMMMMMMMMMWN0d:'.',;:clllllllllllllllllc:::;:clllloxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWKxc,'..,;ccllllllllllllllllllllllc:;;:clllllkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMW0o:,,,,:llllllllc::lllllllllllllllllcc::clllc:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMWNK0kxdol:;,;ccllcccccc;'',;:ccccccllllllccllcc:clllc:cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWNK0Oko:,:c:'.;cc;,'','.''........',,;:cccccccc:ccccccccccclkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWNNX0o;';:,...;:'.''',,,,,''...........,;:c::::;,,;:c::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMW0l;...''....,;'cxkO0000Okkkdc,....','.',;;;;;;;..,:;,',;:;,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWkccc'........;okKNNNNNNNNNNNNX0koooc,.....',...'...;;,...,,'..cKMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMKdkKl........'cONNNNNNNNNNNNNNNNNNXNXOlldolc,......',,;'. ......oNMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMW0kX0:....''.:kKXNNNNNNNNNNNNNNNNNNNNNXKKKXXKd,.....',,;,.. ....:kNMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMWNNNXo......,dXNXXXXXNNNNNNNNNNNXKKKKKKKKKKXX0xdc..'.';;.......,kWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMWKl'....ckKKKKKKXNNNNNNNNNNNNNNNXKXXNNNNNNX0d;....'..';,...;OWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMNd,..,o0NNNXK00KXXXNNNNNNNNNNNKkxxxxkO0KXXO:......'ldl'.;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMXo..,lOXKkddlld0XK0KXNNNNNNNXOdxOxc;:lxOKKo,....'cdxl;o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMXd;..,o0OxOKx:cd0XK0KNNNNNNNNKKNWXxookKKKXx,..'';ldd;;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMNKOc..;xKXNWN0OKNNNX0XNNNNNNNNNNNNNXXXNNNXkc;odlllc,,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMNd'..;dKXNWNNNNNN0kKNNNNNNNNNNNNNNNNNXXXKO0Ooc:'..cKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWXkl;,cx0XNNNNNNXOx0XXXXXXXXXXXXXXXXXXXXXX0o,...':xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWX00KKKXXXXXXXOddOKKKKKXXKXXXKKXXXXKKKKKxc'.,,:OWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWMMMWXKKXXKKKkdoooddkOKKKKKKKKKKKKKK0Oxo:''okx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWNXKKKK00OkxdxkO00000OOO000000Oxddxoc:;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWX0OOOkkkkkkkkkkkkxxxkOOOkxdooxO0KXKl',dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOOOOxdxkOOOkkkkOOkxdolcclxOKWWWXo'.'cx0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kkkkkOOkkkkkxdolc:::clkKNWMMNx;......,lOWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOolooodddddoccc:::cclx0NWMMMWO;.........,lkKWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:'.;c:;:::::::::ccokOKNMMMMMMKl'...........';lkKNWMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWN0d;.....cddllc:::::cdOKNWWMMMMMMMNd'...............',cdOKNWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWWXOdc,... . .;odxkkdc:::cok0NWWMMMMMMMWO:.....................':ldkKNWMMMMMMMMMMM
    MMMMMMMMMMMMMWNX0koc,..        .codxdllol::ldxolkXWWMMMMMXl'..........................,:ok0NWWMMMMMM
    MMMMMMMMWNX0ko:,'.....         ,oddxo,,ldlloo:'':x0KWMWWNx,...............................':oxOXMMMM
    MMWWWN0koc,............       .:ddddl'.':lcc;',cdxxx0NWW0:....................................'xMMMM
    MWXkl:,....................   .lddddo:..',;;;;:dOOkkxOXKl'.....................................dMMMM
    MNd'..........................,oxoodxd:'.,;;;;lOWWNXKOko'......................................dMMMM
    MKc...........................:dxxOKKOxl,'';;,lKMMMMMWKl...............................  ......dMMMM
    Wk,..........................,lxOXWMWN0kl;'..'c0WMMMMWO;............   ...............   ......dWMMM
    Xl...................  ......;o0NMMMMMNOo;,'.,:l0WMMMNo'.............................   .......dWMMM
    0;...........................:xXWMMMMMWOc,,,,,;;lONNWO:.............................   ........dWMMM
    XOkkxkkxkkkkkkkkkkkkkkkkkkkkO0NWMMMMMMWX0OOO0OOO0XNWWXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkkkkkkkkKMMMM
    MMMMMMMMMMMWMMWWMMMMMMMMWWMMWMMMMMMMMMWWWWMWWMMMMMMMMMMMMMMMMMMMMWWWWNXXXXXNNWWMWNXNWMMMMMMMMMMMMMMM
    MMMMMMMMWKdlooodddoddddddxO0dclllodk0NWMMMMMXxkXMMMMMMMMMWXxxKWMXo;::ccccc:::l0WNd,dNWMMMMMMMMMMMMMM
    MMMMMMMMWXkddool'.'cooooookx,.:dddl:;:lONWWNd.'OWMMMMMMMMWk..xWMK;.;x0KKXKKK00NWXc.lNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMWWWNl.;0WMMMMMWO,.oNMMWNKo'.dNWNo.'OWMMMMMMMMWx..xWWK;.cXWWWWWNNNWMMXc.lNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWNd.'kWMMMMMWk'.dXNNXKkc..dNMNo.,OWMMMMMMMMNd.'kMWO,.'cllcccc:lOWWXc.lNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWk'.xWMMMMMNd..';;;,';cd0NMMWx..xWMMMMMMMWK:.:KMWk'.:xxkOOO00KNWWX:.lNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWO,.oNMMMMMNd..cdoc;',cx0NWWMKc.;OWMMWMWWKl.,kWMWk..xWMWMWMMMMMMWNd:xNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMM0;.oNMWWWMWx.'kWWWNKkl;,:ONWWKo;;clodddl;,l0WWWW0;.:kOOOOkkkOXWMXkd0WWMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMXxd0WMWWWMW0llKMMMMMMWXkoONMMWWKklcc:;;cd0NMMMMMNk;''.......;OWMXl;xWMMMMMMMMMMMMMMM
    */
}
